// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	courier "delivery/internal/core/domain/model/courier"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CourierRepo is an autogenerated mock type for the CourierRepo type
type CourierRepo struct {
	mock.Mock
}

type CourierRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *CourierRepo) EXPECT() *CourierRepo_Expecter {
	return &CourierRepo_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, _a1
func (_m *CourierRepo) Add(ctx context.Context, _a1 *courier.Courier) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *courier.Courier) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CourierRepo_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type CourierRepo_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *courier.Courier
func (_e *CourierRepo_Expecter) Add(ctx interface{}, _a1 interface{}) *CourierRepo_Add_Call {
	return &CourierRepo_Add_Call{Call: _e.mock.On("Add", ctx, _a1)}
}

func (_c *CourierRepo_Add_Call) Run(run func(ctx context.Context, _a1 *courier.Courier)) *CourierRepo_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*courier.Courier))
	})
	return _c
}

func (_c *CourierRepo_Add_Call) Return(_a0 error) *CourierRepo_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CourierRepo_Add_Call) RunAndReturn(run func(context.Context, *courier.Courier) error) *CourierRepo_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *CourierRepo) Get(ctx context.Context, id uuid.UUID) (*courier.Courier, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *courier.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*courier.Courier, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *courier.Courier); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*courier.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CourierRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type CourierRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *CourierRepo_Expecter) Get(ctx interface{}, id interface{}) *CourierRepo_Get_Call {
	return &CourierRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *CourierRepo_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *CourierRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *CourierRepo_Get_Call) Return(_a0 *courier.Courier, _a1 error) *CourierRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CourierRepo_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*courier.Courier, error)) *CourierRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllFreeCouriers provides a mock function with given fields: ctx
func (_m *CourierRepo) GetAllFreeCouriers(ctx context.Context) ([]*courier.Courier, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllFreeCouriers")
	}

	var r0 []*courier.Courier
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*courier.Courier, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*courier.Courier); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*courier.Courier)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CourierRepo_GetAllFreeCouriers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllFreeCouriers'
type CourierRepo_GetAllFreeCouriers_Call struct {
	*mock.Call
}

// GetAllFreeCouriers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *CourierRepo_Expecter) GetAllFreeCouriers(ctx interface{}) *CourierRepo_GetAllFreeCouriers_Call {
	return &CourierRepo_GetAllFreeCouriers_Call{Call: _e.mock.On("GetAllFreeCouriers", ctx)}
}

func (_c *CourierRepo_GetAllFreeCouriers_Call) Run(run func(ctx context.Context)) *CourierRepo_GetAllFreeCouriers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *CourierRepo_GetAllFreeCouriers_Call) Return(_a0 []*courier.Courier, _a1 error) *CourierRepo_GetAllFreeCouriers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *CourierRepo_GetAllFreeCouriers_Call) RunAndReturn(run func(context.Context) ([]*courier.Courier, error)) *CourierRepo_GetAllFreeCouriers_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *CourierRepo) Update(ctx context.Context, _a1 *courier.Courier) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *courier.Courier) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CourierRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type CourierRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *courier.Courier
func (_e *CourierRepo_Expecter) Update(ctx interface{}, _a1 interface{}) *CourierRepo_Update_Call {
	return &CourierRepo_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *CourierRepo_Update_Call) Run(run func(ctx context.Context, _a1 *courier.Courier)) *CourierRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*courier.Courier))
	})
	return _c
}

func (_c *CourierRepo_Update_Call) Return(_a0 error) *CourierRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CourierRepo_Update_Call) RunAndReturn(run func(context.Context, *courier.Courier) error) *CourierRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewCourierRepo creates a new instance of CourierRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCourierRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CourierRepo {
	mock := &CourierRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
