// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	order "delivery/internal/core/domain/model/order"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// OrderRepo is an autogenerated mock type for the OrderRepo type
type OrderRepo struct {
	mock.Mock
}

type OrderRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepo) EXPECT() *OrderRepo_Expecter {
	return &OrderRepo_Expecter{mock: &_m.Mock}
}

// Add provides a mock function with given fields: ctx, _a1
func (_m *OrderRepo) Add(ctx context.Context, _a1 *order.Order) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *order.Order) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepo_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type OrderRepo_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *order.Order
func (_e *OrderRepo_Expecter) Add(ctx interface{}, _a1 interface{}) *OrderRepo_Add_Call {
	return &OrderRepo_Add_Call{Call: _e.mock.On("Add", ctx, _a1)}
}

func (_c *OrderRepo_Add_Call) Run(run func(ctx context.Context, _a1 *order.Order)) *OrderRepo_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*order.Order))
	})
	return _c
}

func (_c *OrderRepo_Add_Call) Return(_a0 error) *OrderRepo_Add_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepo_Add_Call) RunAndReturn(run func(context.Context, *order.Order) error) *OrderRepo_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *OrderRepo) Get(ctx context.Context, id uuid.UUID) (*order.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *order.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*order.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *order.Order); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepo_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type OrderRepo_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *OrderRepo_Expecter) Get(ctx interface{}, id interface{}) *OrderRepo_Get_Call {
	return &OrderRepo_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *OrderRepo_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *OrderRepo_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderRepo_Get_Call) Return(_a0 *order.Order, _a1 error) *OrderRepo_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepo_Get_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*order.Order, error)) *OrderRepo_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllInAssignedStatus provides a mock function with given fields: ctx
func (_m *OrderRepo) GetAllInAssignedStatus(ctx context.Context) ([]*order.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllInAssignedStatus")
	}

	var r0 []*order.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*order.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*order.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*order.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepo_GetAllInAssignedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllInAssignedStatus'
type OrderRepo_GetAllInAssignedStatus_Call struct {
	*mock.Call
}

// GetAllInAssignedStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OrderRepo_Expecter) GetAllInAssignedStatus(ctx interface{}) *OrderRepo_GetAllInAssignedStatus_Call {
	return &OrderRepo_GetAllInAssignedStatus_Call{Call: _e.mock.On("GetAllInAssignedStatus", ctx)}
}

func (_c *OrderRepo_GetAllInAssignedStatus_Call) Run(run func(ctx context.Context)) *OrderRepo_GetAllInAssignedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *OrderRepo_GetAllInAssignedStatus_Call) Return(_a0 []*order.Order, _a1 error) *OrderRepo_GetAllInAssignedStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepo_GetAllInAssignedStatus_Call) RunAndReturn(run func(context.Context) ([]*order.Order, error)) *OrderRepo_GetAllInAssignedStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetFirstInCreatedStatus provides a mock function with given fields: ctx
func (_m *OrderRepo) GetFirstInCreatedStatus(ctx context.Context) (*order.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetFirstInCreatedStatus")
	}

	var r0 *order.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*order.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *order.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*order.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepo_GetFirstInCreatedStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFirstInCreatedStatus'
type OrderRepo_GetFirstInCreatedStatus_Call struct {
	*mock.Call
}

// GetFirstInCreatedStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *OrderRepo_Expecter) GetFirstInCreatedStatus(ctx interface{}) *OrderRepo_GetFirstInCreatedStatus_Call {
	return &OrderRepo_GetFirstInCreatedStatus_Call{Call: _e.mock.On("GetFirstInCreatedStatus", ctx)}
}

func (_c *OrderRepo_GetFirstInCreatedStatus_Call) Run(run func(ctx context.Context)) *OrderRepo_GetFirstInCreatedStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *OrderRepo_GetFirstInCreatedStatus_Call) Return(_a0 *order.Order, _a1 error) *OrderRepo_GetFirstInCreatedStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepo_GetFirstInCreatedStatus_Call) RunAndReturn(run func(context.Context) (*order.Order, error)) *OrderRepo_GetFirstInCreatedStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1
func (_m *OrderRepo) Update(ctx context.Context, _a1 *order.Order) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *order.Order) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrderRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type OrderRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *order.Order
func (_e *OrderRepo_Expecter) Update(ctx interface{}, _a1 interface{}) *OrderRepo_Update_Call {
	return &OrderRepo_Update_Call{Call: _e.mock.On("Update", ctx, _a1)}
}

func (_c *OrderRepo_Update_Call) Run(run func(ctx context.Context, _a1 *order.Order)) *OrderRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*order.Order))
	})
	return _c
}

func (_c *OrderRepo_Update_Call) Return(_a0 error) *OrderRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrderRepo_Update_Call) RunAndReturn(run func(context.Context, *order.Order) error) *OrderRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderRepo creates a new instance of OrderRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepo {
	mock := &OrderRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
